# Python with Jupyter 
# Assignment 1

In [2]:
#Below are scenarios from 1 to 20 marked as #1 scenarios
#1 scenario
'''
: You have a list of integers, and you need to find the maximum value in the list.
#a. Question: How would you find the maximum value from the following list?
'''
num = [23, 56, 67, 12, 9.0, 24] #list of numbers
print(max(num)) # to find the maximum value from the list

67


In [3]:
#2 scenario
'''
You need to concatenate a list of strings into a single string, with each string separated by a comma.
a. Question: How would you combine the following list of strings into a single string?
'''
name = ["Anish", "Bob", "Ashish","Rome"]
name2 = ["Ravi", "Deepa", "JJ", "Mohan"]
name_all = name + name2
print(name_all)

['Anish', 'Bob', 'Ashish', 'Rome', 'Ravi', 'Deepa', 'JJ', 'Mohan']


In [4]:
#3 scenario
'''
You have a dictionary where the keys are names and the values are ages. You need to retrieve the age of a specific person.
a. Question: How would you get the age of "Dev" from the following dictionary?
'''
employee_age = {"Jim":30, "Dwight":32, "Micheal":33, "Dev":32} #name and age of employees
print(employee_age["Dev"]) #from emplyee data set finding the age of Dev by specifying it

32


In [5]:
#4 scenario
'''
You need to remove duplicate elements from a list while preserving the original order of elements.
a. Question: How would you remove duplicates from the following list?
'''
age = [12,13,14,16,17,16,19,20] #doubel number 16
age.pop(5) # pop will remove the specified index from the list, counting list element from 0
print(age)

[12, 13, 14, 16, 17, 19, 20]


In [125]:
#5 scenario
'''
You have a NumPy array and need to compute the sum of all its elements.
a. Question: How would you find the sum of elements in the following NumPy array?
'''
import numpy as np #importing numpy 
nparray = np.array([1,2,3,4,5,6]) # nparray name of variable for array
print(nparray)
print(sum(nparray)) 

[1 2 3 4 5 6]
21


In [53]:
#6 scenario
'''
You have a 2D NumPy array and need to get the maximum value from each column.
a. Question: How would you find the maximum values for each column in the following array?
'''
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]]) #columns in 2D, self written
print(max(arr[0]),max(arr[1])) # finding max values from both columns

4 8


In [127]:
#7 scenario
'''
You have a DataFrame and need to sort it by a specific column.
a. Question: How would you sort the DataFrame by the "Age" column?
'''
import numpy as np
import pandas as pd
exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
print(exam_data)

{'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, nan, 9, 20, 14.5, nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}


In [ ]:
#8 scenario
'''
You need to calculate the total sum of a column in a DataFrame.
a. Question: How would you find the sum of the "Sales" column?
''' 
df['Sales'].sum()

In [55]:
#9 scenario
'''
: You need to check if a variable is of type int.
a. Question: How would you verify if a variable x is an integer?
'''
x = 12
print(type(x))

<class 'int'>


In [3]:
#10 scenario
'''
: You have a list of mixed types and need to create separate lists for integers, floats, and strings.
a. Question: How would you categorize the following mixed list into different types?
'''
mix_lists = [12.9,23.1, 45,55,"Anish", "JJ"]
res = sorted(mix_lists, key = lambda ele: (0, int(ele))
                        if ele.isdigit() else (1, ele))
print(str(res))

AttributeError: 'float' object has no attribute 'isdigit'

In [177]:
#11 scenario
'''
You are given a string of comma-separated numbers. You need to convert this string into a list of integers.
a. Question: How would you achieve this conversion?
'''
s = '2, 3.4, 5, 3, 6.2, 4, 7' #string to list of intergers

i = s.split(',')
print(i)
type(i)

['2', ' 3.4', ' 5', ' 3', ' 6.2', ' 4', ' 7']


list

In [147]:
#12 scenario
'''
: You need to reverse the words in a sentence while keeping the order of the words intact.
a. Question: How would you reverse each word in the following sentence?
'''

x = "My name is Anish"
y = x.split(' ') # used the space between the word to slice, so My 0, name 1, is 2, Anish 3
r = y[::-1] # revesed the way it comes in r with :: -1(::-1 indicates show all starting from -1) starting from end, 
            #taking Anish first eg: Anish -1,is -2,name -3, My -4  
e = y[::-1] # checking 
z = ' '.join(r) # joined the words with space ' ' in z 

print(e)
print(z)



['Anish', 'is', 'name', 'My']
Anish is name My


In [83]:
#13 scenario
'''
You need to combine two lists into a dictionary where the elements of the first list are keys and the elements of the second list are values.
a. Question: How would you combine the following lists into a dictionary?
'''

name = ["Anish", "Dev", "Ashish", "Raj"]
Age = [27, 34, 33, 26]
result = {name[i]: Age[i] for i in range(len(name))}
print(str(result))

{'Anish': 27, 'Dev': 34, 'Ashish': 33, 'Raj': 26}


In [9]:
#14 scenario
'''
You are given a list of tuples where each tuple contains a name and an age. You need to sort this list by age.
a. Question: How would you sort the following list of tuples by age?
'''
data = [('Anish', 26), ('Bob', 24), ('JJ', 28),('Nick', 20)]
sorted(data(age))

NameError: name 'age' is not defined

In [103]:
#15 scenario
'''
You have a 2D NumPy array and need to calculate the mean value of each row.
a. Question: How would you compute the mean value for each row in the following array?
'''
import numpy as np
ndarray2 = np.array([[1,2,3],[4,5,6]])
print(ndarray2)
print(np.mean(ndarray2, axis = 1)) #for row use axis =1 and colum axis = 0

[[1 2 3]
 [4 5 6]]
[2. 5.]


In [175]:
#16 scenario
'''
You need to create a NumPy array of size 10 filled with zeros, and then set the fifth element to 5.
a. Question: How would you create and modify the array as described?
'''
import numpy as np
x = np.zeros(10)
print(x)
x[5]


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


0.0

In [117]:
#17 scenario
'''
You have a DataFrame and need to find the median of a numeric column.
a. Question: How would you find the median of the "Scores" column in the following DataFrame?
'''

import numpy as np
import pandas as pd
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, 23, 9, 20, 14.5, 34, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

df = pd.DataFrame(exam_data) # search engine was used 
print(df['score'].median()) 

15.5


In [ ]:
#18 scenario
'''
You need to filter rows where the value in the "Sales" column is above 100 and then sort these rows by "Date" in descending order.
a. Question: How would you filter and sort the DataFrame based on the given criteria?
'''
df['Sales'] = pd.to_datetime(df['Sales'])
df.sort_values(by='Sales', ascending=False)


In [157]:
#19 scenario
'''
: You have a string containing a number and need to convert it to an integer. Additionally, handle 
  the case where the string might not represent a valid integer.
a. Question: How would you safely convert the string "42" to an integer and handle invalid cases?
'''
name = "42"
type(name)

str

In [153]:
#20 scenario
'''
You have a list containing different data types, and you want to separate out all the strings.
a. Question: How would you extract all string elements from the following list?
'''
list1 = ["Anish", 12, 56.9, 23, "Bob"]
list1[0],list1[4]


('Anish', 'Bob')